# Generated by Django 4.1.1 on 2022-10-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_rename_brand_mahsulot_meva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulot',
            old_name='meva',
            new_name='brand',
        ),
    ]
